<?php

class AdminReservarCitaControllerCore extends AdminController
{

    public function __construct()
    {
        $this->bootstrap = true;
        $this->table = 'reservar_cita';
        $this->className = 'ReservarCita';
        $this->lang = false;
        $this->context = Context::getContext();
//        $this->addRowAction('edit');
//        $this->addRowAction('delete');
//        $this->addRowAction('view');

        parent::__construct();


        $this->_join .= 'LEFT JOIN `'._DB_PREFIX_.'employee` ea ON (ea.`id_employee` = a.`id_colaborador` AND a.`id_shop` = '.$this->context->shop->id.')';
        $this->_join .= 'LEFT JOIN `'._DB_PREFIX_.'customer` ec ON (ec.`id_customer` = a.`id_customer` AND a.`id_shop` = '.$this->context->shop->id.')';
        $this->_select .= 'CONCAT_WS(" ",ea.firstname, ea.lastname) as colaborador, ea.firstname as cliente';

        $this->fields_list = array(
            'id_reservar_cita' => array('align' => 'hide', 'class' => 'hide'),
            'fecha_inicio' => array('title' => $this->l('Fecha Apertura'),  'type' => 'date',),
            'hora' => array('title' => $this->l('Hora'),  'havingFilter' => true),
            'colaborador' => array('title' => $this->l('Colaborador'),  'havingFilter' => true),
            'cliente' => array('title' => $this->l('Cliente'),  'havingFilter' => true),
            'product_name' => array('title' => $this->l('Servicio'),  'havingFilter' => true),
        );
        
    }
    public function setMedia($isNewTheme = false)
    {
        parent::setMedia($isNewTheme); // TODO: Change the autogenerated stub

        $this->addJqueryPlugin('autocomplete');
        $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/css/waitMe.min.css');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/waitMe.min.js');
    }

    public function initPageHeaderToolbar()
    {
        if (empty($this->display))
            $this->page_header_toolbar_btn['new_cita'] = array(
                'href' => self::$currentIndex.'&addreservar_cita&token='.$this->token,
                'desc' => $this->l('Crear Cita', null, null, false),
                'icon' => 'process-icon-new'
            );

        parent::initPageHeaderToolbar();
    }

    public function renderForm()
    {

        $this->fields_form = array(
            'legend' => array(
                'title' => $this->l('Cita'),
                'icon' => 'icon-group'
            ),
            'input' => array(),
            'submit' => array(
                'title' => $this->l('Save'),
            )
        );

        $colaboradores = Employee::getEmployees(true);
        $this->context->smarty->assign(array(
            'colaboradores' => $colaboradores
        ));

        return parent::renderForm();
    }

    public function ajaxProcessGetCitasByColaborador()
    {
        $id_colaborador = Tools::getValue('id_colaborador');

        $citas = ReservarCita::getCitasByColadorador($id_colaborador);

        die(json_encode(array(
            "respuesta" => "ok",
            "citas" => $citas
        )));
    }

    public function ajaxProcessGetProductByName()
    {

        $query = Tools::getValue('q', false);
        if ( ! $query or $query == '' or strlen($query) < 1) {
            die();
        }

        if ($pos = strpos($query, ' (ref:')) {
            $query = substr($query, 0, $pos);
        }

        $context = Context::getContext();

        $sql = new DbQuery();
        $sql->select('p.id_product as id, pl.name as text, p.*, product_shop.*, pl.*');
        $sql->from('product', 'p');
        $sql->join(Shop::addSqlAssociation('product', 'p'));
        $sql->leftJoin('product_lang', 'pl', '
			p.`id_product` = pl.`id_product`
			AND pl.`id_lang` = '.(int)$context->language->id.Shop::addSqlRestrictionOnLang('pl')
        );

        $where = '1 ';

        $search_items = explode(' ', $query);
        $research_fields = array('pl.`name`', 'p.`reference`');

        $items = array();
        foreach ($research_fields as $field) {
            foreach ($search_items as $item) {
                $items[$item][] = $field.' LIKE \'%'.pSQL($item).'%\' ';
            }
        }
        $where .= ' AND p.is_virtual = 1 ';
        foreach ($items as $likes) {
            $where .= ' AND ('.implode(' OR ', $likes).') ';
        }

        $sql->where($where);

        $items = Db::getInstance()->executeS($sql, true, false);
        $to_return = array(
            'products' => $items,
            'found' => true
        );
        die(json_encode($to_return));

    }
}

