<?php

class AdminReservarCitaControllerCore extends AdminController
{

    public function __construct()
    {
        $this->bootstrap = true;
        $this->table = 'reservar_cita';
        $this->className = 'ReservarCita';
        $this->lang = false;
        $this->colorOnBackground = true;
        $this->context = Context::getContext();
        $this->addRowAction('edit');
//        $this->addRowAction('delete');
//        $this->addRowAction('view');
        $this->addRowAction('pasar_venta');
        $this->addRowAction('anularcita');

        parent::__construct();


        $this->_join .= 'LEFT JOIN `'._DB_PREFIX_.'employee` ea ON (ea.`id_employee` = a.`id_colaborador` AND a.`id_shop` = '.$this->context->shop->id.')';
        $this->_join .= 'LEFT JOIN `'._DB_PREFIX_.'customer` ec ON (ec.`id_customer` = a.`id_customer` AND a.`id_shop` = '.$this->context->shop->id.')';
        $this->_select .= 'CONCAT_WS(" ",ea.firstname, ea.lastname) as colaborador, ec.firstname as cliente, IF(estado_actual = 0, "Pendiente", IF(estado_actual = 1, "Atendido", IF(estado_actual = 2, "Cancelado", "Facturado"))) as estado, estado_actual';

        $this->_orderBy = 'fecha_inicio';
        $this->_orderWay = 'DESC';

        $this->fields_list = array(
            'id_reservar_cita' => array('align' => 'hide', 'class' => 'hide'),
            'fecha_inicio' => array('title' => $this->l('Fecha Apertura'),  'type' => 'date',),
            'hora' => array('title' => $this->l('Hora'),  'havingFilter' => true),
            'colaborador' => array('title' => $this->l('Colaborador'),  'havingFilter' => true),
            'cliente' => array('title' => $this->l('Cliente'),  'havingFilter' => true),
            'product_name' => array('title' => $this->l('Servicio'),  'havingFilter' => true),
            'estado' => array('title' => $this->l('Estado'),  'havingFilter' => true, 'color' => 'color'),
        );
        
    }

    public function displayAnularcitaLink($token = null, $id)
    {
        $cita = new ReservarCita((int)$id);

        if ($cita->estado_actual != 0){
//            if (($key = array_search($this->action, $this->actions)) !== false) {
//                unset($this->actions[$key]);
//            }
            return false;
        }

        $href = self::$currentIndex.'&'.$this->identifier.'='.(int)$id.'&action=anularcita&token='.($token != null ? $token : $this->token);

        $this->context->smarty->assign(array(
            "href" => $href,
            $this->identifier => $id,
            'action' => "Anular",
            'confirm' => "¿Seguro de anular la cita?",
        ));
//
        return $this->context->smarty->fetch('controllers/reservar_cita/helpers/list/list_action_anularcita.tpl');
    }

    public function processAnularcita()
    {
        if (Validate::isLoadedObject($object = $this->loadObject())) {
            $object->estado_actual = 2;
            $object->update();
        } else {
            $this->errors[] = $this->trans('Error al anular la cita.', array(), 'Admin.Notifications.Error')
                .' <b>'.$this->table.'</b> '.$this->trans('(cannot load object)', array(), 'Admin.Notifications.Error');
        }
        return true;
    }

    public function getList($id_lang, $orderBy = null, $orderWay = null, $start = 0, $limit = null, $id_lang_shop = null)
    {
        parent::getList($id_lang, $orderBy, $orderWay, $start, $limit, $id_lang_shop);

        if ($this->_list) {
            foreach ($this->_list as &$row) {
                if ((int)$row['estado_actual'] == 0){
                    $row['color'] =  "#ffc107"; // rojo
                }
                elseif ((int)$row['estado_actual'] == 1){
                    $row['color'] =  "#25b9d7"; // rojo
                }
                elseif ((int)$row['estado_actual'] == 2){
                    $row['color'] =  "#dd2246"; // rojo
                }
                elseif ((int)$row['estado_actual'] == 3){
                    $row['color'] =  "#72c279"; // rojo
                }

            }
        }
    }

    public function setMedia($isNewTheme = false)
    {
        parent::setMedia($isNewTheme); // TODO: Change the autogenerated stub

        $this->addJqueryPlugin('autocomplete');
        $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/css/waitMe.min.css');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/waitMe.min.js');
    }

    public function initPageHeaderToolbar()
    {
        if (empty($this->display))
            $this->page_header_toolbar_btn['new_cita'] = array(
                'href' => self::$currentIndex.'&addreservar_cita&token='.$this->token,
                'desc' => $this->l('Crear Cita', null, null, false),
                'icon' => 'process-icon-new'
            );

        parent::initPageHeaderToolbar();
    }

    public function renderForm()
    {

        $cita = new ReservarCita((int)Tools::getValue('id_reservar_cita'));
        $customer = new Customer((int)$cita->id_customer);
        $this->fields_form = array(
            'legend' => array(
                'title' => $this->l('Cita'),
                'icon' => 'icon-group'
            ),
            'input' => array(),
            'submit' => array(
                'title' => $this->l('Save'),
            )
        );


        $colaboradores = Employee::getColaboradores(true);
        $tipo_documentos = Tipodocumentolegal::getAllTipDoc();
        $this->context->smarty->assign(array(
            'cita' => $cita,
            'customer' => $customer,
            'colaboradores' => $colaboradores,
            'tipo_documentos' => $tipo_documentos
        ));

        return parent::renderForm();
    }

    public function ajaxProcessGuardarCita()
    {
        $data = Tools::getValue('data');
        $params = array();
        parse_str($data, $params);

        $id_reservar_cita = $params['id_reservar_cita'];


        if (isset($params['id_customer']) && $params['id_customer'] > 0){
            $customer = new Customer((int)$params['id_customer']);
            $customer->id_document = $params['cb_tipo_documento'];
            $customer->num_document = trim($params['txtNumeroDocumento']);
            $customer->firstname = $params['txtNombre'];
            $customer->direccion = $params['txtDireccion'];
            $customer->birthday = Tools::getFormatFechaGuardar($params['birthday']);
            $customer->telefono_celular = $params['celular'];
            $customer->update();
            $id_cliente = $customer->id;
        }
        else{
            $customer = new Customer();
            $customer->id_shop_group = Context::getContext()->shop->id_shop_group;
            $customer->id_shop = Context::getContext()->shop->id;
            $customer->id_gender = 0;
            $customer->id_default_group = (int) Configuration::get('PS_CUSTOMER_GROUP');
            $customer->id_lang = Context::getContext()->language->id;
            $customer->id_risk = 0;
            $customer->firstname = $params['txtNombre'];
            $customer->lastname = "";
            $pass = $this->get('hashing')->hash("123456789", _COOKIE_KEY_);
            $customer->passwd = $pass;
            $customer->last_passwd_gen = date('Y-m-d H:i:s', strtotime('-'.Configuration::get('PS_PASSWD_TIME_FRONT').'minutes'));
            $customer->birthday = Tools::getFormatFechaGuardar($params['birthday']);
            $customer->newsletter = 0;
            $customer->optin = 0;
            $customer->outstanding_allow_amount = 0;
            $customer->show_public_prices = 0;
            $customer->max_payment_days = 0;
//                d(md5(uniqid(rand(), true)));
            $customer->secure_key = md5(uniqid(rand(), true));
            $customer->active = 1;
            $customer->is_guest = 0;
            $customer->deleted = 0;
            $customer->id_document = $params['cb_tipo_documento'];
            $customer->num_document = trim($params['txtNumeroDocumento']);
            $customer->direccion = $params['txtDireccion'] ;
            $customer->telefono_celular = $params['celular'] ;
            $res = $customer->add();
            if ($res){
                $customer->updateGroup(array($customer->id_default_group));
            }

            $id_cliente = $customer->id;
        }

        if (isset($id_reservar_cita) && (int)$id_reservar_cita > 0){
            $obj = new ReservarCita((int)$id_reservar_cita);
        }else{
            $obj = new ReservarCita();
        }
        //formatear fecha con hora 12 horas
        $startdate = $params['fecha_inicio'];
        $myDateTime = DateTime::createFromFormat('d/m/Y h:i A',$startdate);
        $fecha_inicio = $myDateTime->format('Y-m-d H:i:s');
        $hora = $myDateTime->format('h:i A');

        $obj->fecha_inicio = $fecha_inicio;
        $obj->hora = $hora;
        $obj->id_colaborador = $params['id_colaborador'];
        $obj->id_customer = $id_cliente;
        $obj->product_id = $params['product_id'];
        $obj->product_name = $params['product_name'];
        $obj->color = "#000";
        $obj->observacion = $params['observacion'];
        $obj->id_order = 0;
        $obj->estado_actual = $params['estado_actual'];
        $obj->id_employee = $this->context->employee->id;
        $obj->id_shop = $this->context->shop->id;

        if ($id_reservar_cita){
            $res = $obj->update();
        }else{
            $res = $obj->add();
        }
        if ($res){
            die(json_encode(array(
                "respuesta" => "ok",
                "cita" => $obj,

            )));
        }else{
            die(json_encode(array(
                "respuesta" => "error",

            )));
        }

    }


    public function ajaxProcessGetProductByName()
    {

        $query = Tools::getValue('q', false);
        if ( ! $query or $query == '' or strlen($query) < 1) {
            die();
        }

        if ($pos = strpos($query, ' (ref:')) {
            $query = substr($query, 0, $pos);
        }

        $context = Context::getContext();

        $sql = new DbQuery();
        $sql->select('p.id_product as id, pl.name as text, p.*, product_shop.*, pl.*');
        $sql->from('product', 'p');
        $sql->join(Shop::addSqlAssociation('product', 'p'));
        $sql->leftJoin('product_lang', 'pl', '
			p.`id_product` = pl.`id_product`
			AND pl.`id_lang` = '.(int)$context->language->id.Shop::addSqlRestrictionOnLang('pl')
        );

        $where = '1 ';

        $search_items = explode(' ', $query);
        $research_fields = array('pl.`name`', 'p.`reference`');

        $items = array();
        foreach ($research_fields as $field) {
            foreach ($search_items as $item) {
                $items[$item][] = $field.' LIKE \'%'.pSQL($item).'%\' ';
            }
        }
        $where .= ' AND p.is_virtual = 1 ';
        foreach ($items as $likes) {
            $where .= ' AND ('.implode(' OR ', $likes).') ';
        }

        $sql->where($where);

        $items = Db::getInstance()->executeS($sql, true, false);
        $to_return = array(
            'products' => $items,
            'found' => true
        );
        die(json_encode($to_return));

    }
}

