<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6zcgckr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6zcgckr/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6zcgckr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6zcgckr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6zcgckr\appProdProjectContainer(array(
    'container.build_hash' => '6zcgckr',
    'container.build_id' => '352bdbf1',
    'container.build_time' => 1565637130,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6zcgckr');
